# to use this file, build an s2i image first:
# s2i build -e SECRET_KEY_BASE=<SHOULD MATCH the one in .env> . hammady/centos-rvm podcastgen:s2i
# on subsequent builds:
# s2i build --incremental -e SECRET_KEY_BASE=<SHOULD MATCH the one in .env> . hammady/centos-rvm podcastgen:s2i
# then finally:
# docker-compose -f docker-compose-s2i.yml up
version: '3'
services:
  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=podcastgen_development
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  worker:
    image: podcastgen:s2i
    environment:
      - PROCTYPE=worker
    env_file:
      - .env
    links:
      - postgres
  web:
    image: podcastgen:s2i
    environment:
      - PROCTYPE=web
    env_file:
      - .env
    ports:
      - "3000:8080"
    links:
      - postgres
